<?php
/*
 * update_ajax_cart.phtml
 * Improntus. 3rd November, 2025.
 */

/**
 * @var \Improntus\UpdateCartAjax\Block\Cart\Item\AjaxCartConfig $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 * @var \Magento\Quote\Model\Quote\Item $item
 * @var \Magento\Framework\Escaper $escaper
 */

$item = $block->getItem();
$sku = $item?->getSku() ?? '';
?>

<?php if ($block->isEnabled() && $sku): ?>
    <?php $ajaxTriggerMode = $block->getAjaxTriggerMode(); ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "ajaxCart": {
                    "productId": "<?= $escaper->escapeJs($sku) ?>",
                    "allowedModes" : <?= /* @noEscape */ $block->getAllowedModes() ?>,
                    "triggerMode": "<?= $escaper->escapeJs($ajaxTriggerMode) ?>",
                    "increaseQtySelector": "#<?= $escaper->escapeJs($item->getId()) ?>-upt",
                    "decreaseQtySelector": "#<?= $escaper->escapeJs($item->getId()) ?>-dec",
                    "validationURL" : "<?= $escaper->escapeJs($block->getUrl('checkout/cart/updateItemQty')) ?>",
                    "updateCartActionContainer": "#update_cart_action_container"
                }
            }
        }
    </script>

    <?php if ($block->getHideButton()): ?>
        <?php $style = <<<style
            [data-cart-item-update],
            div.cart.main.actions .text-divider {
                display: none;
            }
        style; ?>
        <?= /* @noEscape */ $secureRenderer->renderTag('style', ['type' => 'text/css'], $style, false) ?>
    <?php endif; ?>
<?php endif; ?>